"""empty message

Revision ID: 2cd773c8c555
Revises: 
Create Date: 2020-03-06 14:41:05.154465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd773c8c555'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contents_author', table_name='contents')
    op.create_index(op.f('ix_contents_author'), 'contents', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_author'), table_name='contents')
    op.create_index('ix_contents_author', 'contents', ['author'], unique=True)
    # ### end Alembic commands ###
